config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :recepts

  
  

  

  map.root :controller => "recepts"

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/category.rb
class Category < ActiveRecord::Base
  # belongs_to :recept

  has_many :categories_recepts
  has_many :recept, :through => :categories_recepts
  
  # has_and_belongs_to_many :recept, :join_table => "categories_recepts"

  validates_presence_of :name
  validates_length_of :name, :within => 2..30
  validates_uniqueness_of :name, :on => :create, :message => "već postoji"

end

app/views/shared/_footer.html.erb
<p>Footer</p>

app/views/shared/_kategorije.html.erb
<div id="kat_label">Kategorije:</div>

<%
	li_id = 'kat_link'
	categories = ""
	categories += "<ul>"
	# Sve kat.
	categories += "<li class='#{li_id}'>"
	categories += "<i>" + link_to("Sve", recepts_path) + " (#{Recept.count})" + "</i>"
	categories += "</li>\n"

	Category.find(:all, :order => "name").each { |category|
		categories += "<li class='#{li_id}'>"
		categories += link_to(category.name, "/" + params[:controller] + "/?kat_id=" + category.id.to_s) + " (#{category.recept_ids.count})"
		categories += "</li>\n"
	}
	# Ostale kat.
	@ostale_cats  = Category.find(:all, :include => 'recept', :conditions => 'recepts.id = NULL')
	@ostale_count = begin
		@ostale_cats.categories_recepts.count
	rescue Exception => e
		0
	end

	categories  += "<li class='#{li_id}'>"
	categories  += "<i>" + link_to("Ostali recepti", "/recepts/?kat_id=ostali") + " (#{@ostale_count})" + "</i>"
	categories  += "</li>\n"

	categories += "</ul>\n"
-%>
<%= categories %>

app/views/shared/_recept_template.erb
*Sastojci:*
- 50 dag ...
- 
- 

*Priprema:*
...

app/views/shared/_sidebar.html.erb
<%= render :partial => 'shared/kategorije' %>